# Fly.io deployment configuration for BrightMatter Oracle Backend

app = "brightmatter-oracle"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[secrets]
  # Set these with: fly secrets set KEY=value
  # FLOW_SIGNER_KEY = "your_private_key_here"
  # FLOW_ACCESS_NODE = "https://access.mainnet.nodes.onflow.org:9000"
  # FORTE_API_KEY = "your_forte_api_key"
  # FORTE_API_SECRET = "your_forte_api_secret"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

