app = "brightmatter-frontend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  VITE_API_URL = "https://brightmatter-oracle.fly.dev"
  VITE_FLOW_NETWORK = "mainnet"
  VITE_CAMPAIGN_ESCROW_ADDRESS = "0x14aca78d100d2001"
  VITE_CREATOR_PROFILE_ADDRESS = "0x14aca78d100d2001"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
